---
env:
  PANTS_CONFIG_FILES: "['pants.toml', 'pants.ci.toml']"
  BUILDKITE_PLUGIN_VAULT_ENV_SECRET_PREFIX: "secret/data/buildkite/env"

steps:
  - label: ":docker::cloudsmith: Build and Upload Docker Containers"
    command:
      - make image-push
    plugins:
      - grapl-security/vault-login#v0.1.0
      - grapl-security/vault-env#v0.1.0:
          secrets:
            - CLOUDSMITH_API_KEY
      - docker-login#v2.0.1:
          username: grapl-cicd
          password-env: CLOUDSMITH_API_KEY
          server: docker.cloudsmith.io
    agents:
      queue: "docker"
