env:
  PANTS_CONFIG_FILES: "['pants.toml', 'pants.ci.toml']"
  BUILDKITE_PLUGIN_VAULT_ENV_SECRET_PREFIX: "secret/data/buildkite/env"

steps:
  - label: ":lint-roller::bash: Lint Bash"
    command:
      - make lint-bash
    plugins:
      - grapl-security/vault-login#v0.1.0
      - grapl-security/vault-env#v0.1.0:
          secrets:
            - codecov-buildkite-plugin/TOOLCHAIN_AUTH_TOKEN

  - label: ":lint-roller::docker: Lint Dockerfile"
    command:
      - make lint-docker

  - label: ":lint-roller::buildkite: Lint Plugin"
    command:
      - make lint-plugin

  - label: ":lint-roller::buildkite: Test Plugin"
    command:
      - make test-plugin

  - label: ":lint-roller: Lint HCL"
    command:
      - make lint-hcl

  - label: ":docker: Build Image"
    command:
      - make image
